public class Commons_ContactWrapper {
    Public String contactId{set;get;}
    Public String unitname{set;get;}
    public string unitid{set;get;}
    Public String recordType{set;get;}
    Public String firstName{set;get;}
    Public String Lastname{set;get;}
    Public String PreferredName{set;get;}
    Public String PreviousName{set;get;}
    Public String Gender{set;get;}
    Public Decimal BirthYear{set;get;}
    Public string Phone{set;get;}
    Public String CountryofBirth{set;get;}
    Public String Citizenship{set;get;}
    Public String OtherCitizenship1{set;get;}
    Public String OtherCitizenship2{set;get;}
    Public String PreferredLanguage{set;get;}
    Public String OtherLanguage1{set;get;}
    Public String OtherLanguage2{set;get;}
    Public String Allergies{set;get;}
    Public String CriticalMedications{set;get;}
    Public String OtherMedicalNotes{set;get;}
    Public String GatewayDatabaseContactID{set;get;}
    Public String Notes{set;get;}
    Public String OtherMessaging{set;get;}
    Public String Email{set;get;}
    Public String OtherActiveEmail{set;get;}
    Public String npe01AlternateEmail{set;get;}
    Public String PassportCountry{set;get;}
    Public String VisaType{set;get;}
    Public String VisaExpirationDate{set;get;}
    Public String PrimaryRole{set;get;}
    Public String AdditionalRole1{set;get;}
    Public String AdditionalRole2{set;get;}
    Public String Title{set;get;}
    Public String OtherLanguage3{set;get;}
    Public String OtherLanguage4{set;get;}
    Public String Spouse{set;get;}
    Public String MaritalStatus{set;get;}
    Public Date DateofMarriage{set;get;}
    Public string EmailType {set;get;}
    public string preferWorkEmail {set;get;}
    Public string AlternateEmail {set;get;}
    Public String SkypeID{set;get;}
    Public String GatewayAccountCode{set;get;}
    Public String SendingGateway{set;get;}
    Public String npe01PrimaryAddressType{set;get;}
    Public String npe01SecondaryAddressType{set;get;}
    Public String MailingAddress{set;get;}
    public String MailingStreet{set;get;}
    public String MailingCity{set;get;}
    public String MailingState{set;get;}
    public String MailingCountry{set;get;}
    public String MailingPostalCode{set;get;}
    public String OtherStreet{set;get;}
    public String OtherCity{set;get;}
    public String OtherState{set;get;}
    public String OtherCountry{set;get;}
    Public String OtherAddress{set;get;}
    Public String OtherPostalCode{set;get;}
    Public String GPSLocation{set;get;}
    Public String HighestLevelofEducation{set;get;}
    Public String AreaofStudy{set;get;}
    Public Date MembershipStartDate{set;get;}
    Public Date OriginalFieldDepartureDate{set;get;}
    Public Date CurrentRoleAppointmentDate{set;get;}
    Public String CurrentCountryiftraveling{set;get;}
    Public String HomeCountryPhoneNumber{set;get;}
    Public String WhatsAppPhoneNumber{set;get;}
    Public String PrimaryFieldPhoneNumber{set;get;}
    Public String Seconded{set;get;}
    Public String SecondmentDetails{set;get;}
    Public String CLL{set;get;}
    Public String PreferredCommunication{set;get;}
    Public String PrimaryAffiliation{set;get;}
    Public String SecondaryAffiliation{set;get;}
    Public String Fulltime{set;get;}
    Public Date DigitalSecurityTraining{set;get;}
    Public Date CSTInitialTraining{set;get;}
    Public String CSTAgreementFile{set;get;}
    Public Date CSTCompleted{set;get;}
    Public Date OSTCompleted{set;get;}
    Public Date FSTCompleted{set;get;}
    Public String FamilyFund{set;get;}
    Public String DayofPrayer{set;get;}
    Public String InternationalNews{set;get;}
    Public String ExpectedHSGradDate{set;get;}
    Public String CurrentSchoolType{set;get;}
    Public String SchoolName{set;get;}
    Public String SpecialEducationNeeds{set;get;}
    Public String LivesatHome{set;get;}
    Public Date Birthdate{set;get;}
    Public String FieldforeveryContactRecord{set;get;}
    Public String FieldforStandardContactRecordsOnly{set;get;}
    Public String FieldforDependentContactRecordsOnly{set;get;}
    Public String MaybefutureCommonschanges{set;get;}
    Public String Noteincludedorextracarerequired{set;get;}
    Public String Team{set;get;}
    Public String Area{set;get;}
    Public String Region{set;get;}
    Public string dependentId{set;get;}
    Public String dEducation{set;get;}
    Public Boolean dOnfield{set;get;}
    public String RelationshipId{set;get;}
    Public String RelationshipContact{set;get;}
    Public String RelatedContact{set;get;}
    Public String relationType{set;get;}
    Public String Status{set;get;}
    
    public Commons_ContactWrapper(){
        this.contactId=contactId;
        this.unitname=unitname;
        this.unitid=unitid;
        this.recordType=recordType;
        this.firstName= firstName;
        this.Lastname= Lastname;
        this.PreferredName=PreferredName;
        this.PreviousName=PreviousName;
        this.Gender=Gender;
        this.BirthYear=BirthYear;
        this.Phone=Phone;
        this.CountryofBirth=CountryofBirth;
        this.Citizenship=Citizenship;
        this.OtherCitizenship1=OtherCitizenship1;
        this.OtherCitizenship2=OtherCitizenship2;
        this.PreferredLanguage=PreferredLanguage;
        this.OtherLanguage1=OtherLanguage1;
        this.OtherLanguage2=OtherLanguage2;
        this.Allergies=Allergies;
        this.CriticalMedications=CriticalMedications;
        this.OtherMedicalNotes=OtherMedicalNotes;
        this.GatewayDatabaseContactID=GatewayDatabaseContactID;
        this.Notes=Notes;
        this.OtherMessaging=OtherMessaging;
        this.Email= Email;
        this.OtherActiveEmail=OtherActiveEmail;
        this.npe01AlternateEmail=npe01AlternateEmail;
        this.PassportCountry=PassportCountry;
        this.VisaType=VisaType;
        this.VisaExpirationDate=VisaExpirationDate;
        this.PrimaryRole=PrimaryRole;
        this.AdditionalRole1=AdditionalRole1;
        this.AdditionalRole2=AdditionalRole2;
        this.Title=Title;
        this.OtherLanguage3=OtherLanguage3;
        this.OtherLanguage4=OtherLanguage4;
        this.Spouse=Spouse;
        this.MaritalStatus=MaritalStatus;
        this.DateofMarriage=DateofMarriage;
        this.EmailType=EmailType;
        this.preferWorkEmail=preferWorkEmail;
        this.AlternateEmail=AlternateEmail;
        this.SkypeID=SkypeID;
        this.GatewayAccountCode=GatewayAccountCode;
        this.SendingGateway=SendingGateway;
        this.npe01PrimaryAddressType=npe01PrimaryAddressType;
        this.npe01SecondaryAddressType=npe01SecondaryAddressType;
        this.MailingAddress=MailingAddress;
        this.OtherAddress=OtherAddress;
        this.GPSLocation=GPSLocation;
        this.HighestLevelofEducation=HighestLevelofEducation;
        this.AreaofStudy=AreaofStudy;
        this.MembershipStartDate=MembershipStartDate;
        this.OriginalFieldDepartureDate=OriginalFieldDepartureDate;
        this.CurrentRoleAppointmentDate=CurrentRoleAppointmentDate;
        this.CurrentCountryiftraveling=CurrentCountryiftraveling;
        this.HomeCountryPhoneNumber=HomeCountryPhoneNumber;
        this.WhatsAppPhoneNumber=WhatsAppPhoneNumber;
        this.PrimaryFieldPhoneNumber=PrimaryFieldPhoneNumber;
        this.Seconded=Seconded;
        this.SecondmentDetails=SecondmentDetails;
        this.CLL=CLL;
        this.PreferredCommunication=PreferredCommunication;
        this.PrimaryAffiliation=PrimaryAffiliation;
        this.SecondaryAffiliation=SecondaryAffiliation;
        this.Fulltime=Fulltime;
        this.DigitalSecurityTraining=DigitalSecurityTraining;
        this.CSTInitialTraining=CSTInitialTraining;
        this.CSTAgreementFile=CSTAgreementFile;
        this.CSTCompleted=CSTCompleted;
        this.OSTCompleted=OSTCompleted;
        this.FSTCompleted=FSTCompleted;
        this.FamilyFund=FamilyFund;
        this.DayofPrayer=DayofPrayer;
        this.InternationalNews=InternationalNews;
        this.ExpectedHSGradDate=ExpectedHSGradDate;
        this.CurrentSchoolType=CurrentSchoolType;
        this.SpecialEducationNeeds=SpecialEducationNeeds;
        this.LivesatHome=LivesatHome;
        this.Birthdate=Birthdate;
        this.FieldforeveryContactRecord=FieldforeveryContactRecord;
        this.FieldforStandardContactRecordsOnly=FieldforStandardContactRecordsOnly;
        this.FieldforDependentContactRecordsOnly=FieldforDependentContactRecordsOnly;
        this.MaybefutureCommonschanges=MaybefutureCommonschanges;
        this.Noteincludedorextracarerequired=Noteincludedorextracarerequired;
        this.Team=Team;
        this.Area=Area;
        this.Region=Region;
        this.RelationshipId=RelationshipId;
        this.RelationshipContact=RelationshipContact;
        this.RelatedContact=RelatedContact;
        this.relationType=relationType;
        this.Status=Status;
    }
}